version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin1

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin1
    depends_on:
      - mongo

  server:
    build: server/
    ports:
      - 8080:8080
    depends_on:
      - mongo

volumes:
  mongo_data:
